version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: delivery_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  osrm:
    image: ghcr.io/project-osrm/osrm-backend:latest
    container_name: osrm_central_fd
    ports:
      - "5000:5000"
    volumes:
      - ./data/osrm:/data
    command: >
      osrm-routed --algorithm mld
      --max-table-size 5000
      /data/central-fed-district-260318.osrm
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: .
    container_name: delivery_backend
    ports:
      - "8080:8080"
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://postgres:postgres@db:5432/delivery_db
      OSRM_URL: http://osrm:5000
      DEBUG: "true"
    volumes:
      - ./app:/app
      db:
        condition: service_healthy
      osrm:
        condition: service_started
    command: >
      sh -c "
        cd /app &&
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8080 --reload
      "
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: