"""Add users table

Revision ID: 38d69739e913
<<<<<<< HEAD
Revises:
Create Date: 2026-03-22 20:04:14.005586

"""

=======
Revises: 
Create Date: 2026-03-22 20:04:14.005586

"""
>>>>>>> 3b5ef1822135ef22af73229f1ddceebf43e6c1bb
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD
revision: str = "38d69739e913"
=======
revision: str = '38d69739e913'
>>>>>>> 3b5ef1822135ef22af73229f1ddceebf43e6c1bb
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
<<<<<<< HEAD

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=225), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
        sa.UniqueConstraint("email", name=op.f("uq__users__email")),
    )
=======
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('email', name=op.f('uq__users__email'))
    )
    # ### end Alembic commands ###
>>>>>>> 3b5ef1822135ef22af73229f1ddceebf43e6c1bb


def downgrade() -> None:
    """Downgrade schema."""
<<<<<<< HEAD

    op.drop_table("users")
=======
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
>>>>>>> 3b5ef1822135ef22af73229f1ddceebf43e6c1bb
